### PR TITLE
added solr php extension

### PR DESCRIPTION
**Pull request by ayanozturk**
https://github.com/cloudfoundry/binary-builder/issues/9

### CODE REVIEW

**Comment by RochesterinNYC** [comment]
@ayanozturk thanks for the PR! I notice in the solr [changelog](https://pecl.php.net/package-changelog.php?package=solr) that PHP 7 Support seems to be in `2.4.0`. If this is the case, could you please update this PR to also include `solr` in the PHP 7 recipe?

**Comment by RochesterinNYC** [comment]
Thanks for updating the PHP7 recipe as well.

**Comment by frost-concourse** [comment]
thank you! :)

**Comment by ayanozturk** [comment]
thank you! :)

**Pull request merged**
