### PR TITLE
Fix ioncube & phalcon for PHP 7.1

### PR DESCRIPTION
**Pull request by dmikusa-pivotal**

### CODE REVIEW

**Comment by dmikusa-pivotal** [comment]
For https://github.com/cloudfoundry/php-buildpack/issues/250

**Comment by dgodd** [comment]
@dmikusa-pivotal Do we really always want ioncube and phalcon? What about 5.x ?

Also why delete the test?

**Comment by dmikusa-pivotal** [comment]
>Do we really always want ioncube and phalcon? What about 5.x ?

Yes, I believe we should.  I think they were only excluded because support from those extensions was a little slow.  From the comments, it looks like we meant to go back and re-enable it once the extensions were upgraded but just never did.

>Also why delete the test?

I deleted the test because after removing the tests for excluding ioncube & phalcon, it was the same as the standard php7 test.

**Comment by dgodd** [comment]
OK. I'll schedule this

**Pull request merged**
