### PR TITLE
Geoip extension

### PR DESCRIPTION
**Pull request by dmikusa-pivotal**
I've added support for the geoip extension, plus support for downloading the required geoip databases.  There's an option to download at build time and package the "lite" version of the DB with the produced PHP binaries.  There's also the option to just package the scripts to download the files, so that those can be run during staging.  I plan to add something to the PHP build pack to take advantage of these scripts and easily run them at staging.  That'll be another pull request, hopefully soon.

### CODE REVIEW

**Comment by sclevine** [comment]
Awesome, thanks Dan!

**Comment by dgodd** [comment]
@dmikusa-pivotal @sclevine We have reverted this since it broke the build.

eg. https://buildpacks.ci.cf-app.com/teams/main/pipelines/binary-builder/jobs/binary-builder-specs/builds/76

Also I believe for this to be useful we also had to include the geoip pecl ; which only works for PHP 5.x.

**Comment by sclevine** [comment]
@dmikusa-pivotal could you address the failures?

Also, what are your thoughts on the incompatibility with PHP 7?

**Comment by dmikusa-pivotal** [comment]
The error showing up, `Failure/Error: expect(tar_contains_file('php/lib/php/extensions/*/geoip.so')).to eq true`, appears to be saying that the extension file wasn't built.

This happened while testing and it was usually when the yml file that specifies which PHP extensions to build was pointing to the wrong place and thus the yml file didn't have geoip listed.

**Comment by dmikusa-pivotal** [comment]
>Also I believe for this to be useful we also had to include the geoip pecl ; which only works for PHP 5.x.

Not sure I follow this.  This PR builds the geoip pecl extension.  It was tested w/version 1.1.1 which has PHP 7 support.

https://pecl.php.net/package-changelog.php?package=geoip&release=1.1.1

**Pull request merged**
